# Form implementation generated from reading ui file 'TExtractor.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 816)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.patternText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.patternText.setGeometry(QtCore.QRect(90, 10, 611, 51))
        self.patternText.setPlainText("")
        self.patternText.setOverwriteMode(False)
        self.patternText.setObjectName("patternText")
        self.inputFileText = QtWidgets.QLineEdit(self.centralwidget)
        self.inputFileText.setGeometry(QtCore.QRect(90, 100, 611, 20))
        self.inputFileText.setObjectName("inputFileText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_2.setObjectName("label_2")
        self.outputFileText = QtWidgets.QLineEdit(self.centralwidget)
        self.outputFileText.setGeometry(QtCore.QRect(90, 130, 611, 20))
        self.outputFileText.setObjectName("outputFileText")
        self.previewLog = QtWidgets.QPushButton(self.centralwidget)
        self.previewLog.setGeometry(QtCore.QRect(30, 160, 91, 31))
        self.previewLog.setObjectName("previewLog")
        self.outputDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.outputDataButton.setGeometry(QtCore.QRect(260, 160, 91, 31))
        self.outputDataButton.setObjectName("outputDataButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.textDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.textDisplay.setGeometry(QtCore.QRect(10, 200, 691, 541))
        self.textDisplay.setObjectName("textDisplay")
        self.previewData = QtWidgets.QPushButton(self.centralwidget)
        self.previewData.setGeometry(QtCore.QRect(150, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.previewData.setFont(font)
        self.previewData.setObjectName("previewData")
        self.headerText = QtWidgets.QLineEdit(self.centralwidget)
        self.headerText.setGeometry(QtCore.QRect(90, 70, 611, 20))
        self.headerText.setObjectName("headerText")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_4.setObjectName("label_4")
        self.overwriteFile = QtWidgets.QCheckBox(self.centralwidget)
        self.overwriteFile.setGeometry(QtCore.QRect(380, 170, 151, 18))
        self.overwriteFile.setObjectName("overwriteFile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Input File"))
        self.label_2.setText(_translate("MainWindow", "Output File"))
        self.previewLog.setText(_translate("MainWindow", "Preview Log"))
        self.outputDataButton.setText(_translate("MainWindow", "Output Data"))
        self.label_3.setText(_translate("MainWindow", "Regex Pattern"))
        self.previewData.setText(_translate("MainWindow", "Preview Data"))
        self.label_4.setText(_translate("MainWindow", "Data Header"))
        self.overwriteFile.setText(_translate("MainWindow", "Overwrite Output File"))
