# Form implementation generated from reading ui file 'TExtractor.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 684)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setPatternButton = QtWidgets.QPushButton(self.centralwidget)
        self.setPatternButton.setGeometry(QtCore.QRect(480, 10, 75, 23))
        self.setPatternButton.setObjectName("setPatternButton")
        self.pattern = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pattern.setGeometry(QtCore.QRect(70, 10, 391, 51))
        self.pattern.setPlainText("")
        self.pattern.setOverwriteMode(False)
        self.pattern.setObjectName("pattern")
        self.inputFileText = QtWidgets.QLineEdit(self.centralwidget)
        self.inputFileText.setGeometry(QtCore.QRect(70, 70, 391, 20))
        self.inputFileText.setObjectName("inputFileText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_2.setObjectName("label_2")
        self.outputFileText = QtWidgets.QLineEdit(self.centralwidget)
        self.outputFileText.setGeometry(QtCore.QRect(70, 100, 391, 20))
        self.outputFileText.setObjectName("outputFileText")
        self.loadInputFile = QtWidgets.QPushButton(self.centralwidget)
        self.loadInputFile.setGeometry(QtCore.QRect(480, 70, 75, 23))
        self.loadInputFile.setObjectName("loadInputFile")
        self.processDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.processDataButton.setGeometry(QtCore.QRect(480, 100, 75, 23))
        self.processDataButton.setObjectName("processDataButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 61, 41))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.textDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.textDisplay.setGeometry(QtCore.QRect(20, 140, 541, 491))
        self.textDisplay.setObjectName("textDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.setPatternButton.setText(_translate("MainWindow", "Set Pattern"))
        self.label.setText(_translate("MainWindow", "Input File"))
        self.label_2.setText(_translate("MainWindow", "Output File"))
        self.loadInputFile.setText(_translate("MainWindow", "Load File"))
        self.processDataButton.setText(_translate("MainWindow", "Output Data"))
        self.label_3.setText(_translate("MainWindow", "Regex Pattern"))
